const nodemailer = require('nodemailer');
const randomToken = require('rand-token');
const Response = require('../utils/responseHandler');
require('dotenv').config();

class sendEMail {
    /**
     * The constructor function is a special function that is used to create and initialize an object
     * created within a class.
     * @param email - The email address of the user.
     * @param token - The token that was generated by the server.
     */
    constructor(email, token) {
        this.email = email;
        this.token = token;
    }

    static mailFunction = (details, result) => {
        const resetLink = details.serverUrl + '/api/v1/reset-password?token=' + details.token
        const htmlMessage = '<p>You Recently requested for reset password, kindly use this <a href="' +
            resetLink + '">link</a> to reset your password. <br> <hr> or Copy and paste the link below in your browser <br> ' +
            resetLink + ' </p>';
        const mail = nodemailer.createTransport({
            service: 'smtp',
            host: process.env.MAIL_HOST,
            port: process.env.MAIL_PORT,
            secure: process.env.MAIL_SECURE,
            auth: {
                user: process.env.MAIL_USERNAME, // Your email id
                pass: process.env.MAIL_PASSWORD // Your password
            }
        });
        const mailOptions = {
            from: process.env.MAIL_FROM_ADDRESS, // sender address
            to: details.email,
            subject: 'Reset Password Link - ' + process.env.APP_NAME, // Subject line
            html: htmlMessage
        };
        mail.sendMail(mailOptions, function(err, info) {
            if (err) {
                console.log(err)
                    //process.exit(1);
                return;
            } else {
                result(null, info);
                return;
            }
        });
    }
}



module.exports = sendEMail;