const nodemailer = require('nodemailer');
const randomToken = require('rand-token');
const Response = require('../utils/responseHandler');

class sendEMail {
    /**
     * The constructor function is a special function that is used to create and initialize an object
     * created within a class.
     * @param email - The email address of the user.
     * @param token - The token that was generated by the server.
     */
    constructor(email, token) {
        this.email = email;
        this.token = token;
    }

    static mailFunction = (details, result) => {
        const mail = nodemailer.createTransport({
            service: 'smtp',
            host: "mail.hangoutpadie.com",
            port: 465,
            secure: true, // tru
            auth: {
                user: 'no-reply@hangoutpadie.com', // Your email id
                pass: '7kQG.%l8Au_*' // Your password
            }
        });
        const mailOptions = {
            from: 'no-reply@hangoutpadie.com',
            to: details.email,
            subject: 'Reset Password Link - apexHauz',
            html: '<p>You requested for reset password, kindly use this <a href="http://localhost:4000/reset-password?token=' + details.token + '">link</a> to reset your password</p>'
        };
        mail.sendMail(mailOptions, function(err, info) {
            if (err) {
                console.log(err)
                    //process.exit(1);
                return;
            } else {
                result(null, info);
                return;
            }
        });
    }
}



module.exports = sendEMail;